# This is a Render YAML configuration file for deploying a Django backend
services:
  - type: web
    name: drinks-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: pip install gunicorn && gunicorn drinks_backend.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    branch: main
    rootDir: drinks_backend
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: drinks_backend.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: false