# Generated by Django 5.2 on 2025-05-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customerinfo_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktailscategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='drinkscategory',
            name='image',
        ),
    ]
