# Generated by Django 5.2 on 2025-05-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cash', max_length=20),
        ),
    ]
