# Generated by Django 5.2 on 2025-05-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cocktailscategory_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='cost',
            new_name='price',
        ),
    ]
