# Generated by Django 5.2 on 2025-05-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_cost_drinks_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='image',
        ),
    ]
