# Generated by Django 5.2 on 2025-05-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_offer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
