# Generated by Django 5.2 on 2025-05-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_offer_start_date_alter_offer_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktails',
            name='time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
