# Generated by Django 5.2 on 2025-05-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_reorder_point_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zip_code',
        ),
    ]
