# Generated by Django 5.2 on 2025-05-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cocktails_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed'), ('bogo', 'Bogo')], default='percentage', max_length=50),
        ),
    ]
