# Generated by Django 5.2 on 2025-05-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_offer_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('mpesa', 'MPesa'), ('cash', 'Cash')], default='m-pesa', max_length=100),
        ),
    ]
