
-- Add more cocktail recipes to give customers more variety
INSERT INTO public.cocktail_recipes (name, description, ingredients, instructions, prep_time, difficulty, image_url, category) VALUES
('Espresso Martini', 'A sophisticated coffee cocktail perfect for evening drinks', '2 oz Vodka, 1 oz Coffee Liqueur, 1 oz Fresh Espresso, 0.5 oz Simple Syrup, Coffee beans for garnish', '1. Brew fresh espresso and let cool slightly. 2. Add all ingredients to shaker with ice. 3. Shake vigorously for 15 seconds. 4. Double strain into chilled martini glass. 5. Garnish with 3 coffee beans.', 5, 'Medium', 'https://images.unsplash.com/photo-1514933651103-005eec06c04b', 'Modern'),
('Manhattan', 'Classic whiskey cocktail with sweet vermouth and bitters', '2 oz Bourbon Whiskey, 1 oz Sweet Vermouth, 2 dashes Angostura Bitters, Maraschino cherry for garnish', '1. Add whiskey, vermouth, and bitters to mixing glass with ice. 2. Stir well for 30 seconds. 3. Strain into chilled coupe glass. 4. Garnish with maraschino cherry.', 3, 'Easy', 'https://images.unsplash.com/photo-1578911373434-0cb395d2cbfb', 'Classic'),
('Negroni', 'Italian aperitif with gin, Campari, and sweet vermouth', '1 oz Gin, 1 oz Campari, 1 oz Sweet Vermouth, Orange peel for garnish', '1. Add all ingredients to rocks glass with ice. 2. Stir gently. 3. Express orange peel oils over drink and drop in glass.', 2, 'Easy', 'https://images.unsplash.com/photo-1544148103-0773bf10d330', 'Classic'),
('Cosmopolitan', 'Elegant pink cocktail made famous in the 90s', '1.5 oz Vodka, 0.5 oz Triple Sec, 1 oz Cranberry Juice, 0.5 oz Fresh Lime Juice, Lime wheel for garnish', '1. Add all ingredients to shaker with ice. 2. Shake well. 3. Strain into chilled martini glass. 4. Garnish with lime wheel.', 3, 'Easy', 'https://images.unsplash.com/photo-1580885068218-5c2f0b5bb0d3', 'Modern'),
('Moscow Mule', 'Refreshing vodka cocktail served in copper mug', '2 oz Vodka, 0.5 oz Fresh Lime Juice, 4 oz Ginger Beer, Lime wedge and candied ginger for garnish', '1. Add vodka and lime juice to copper mug with ice. 2. Top with ginger beer. 3. Stir gently. 4. Garnish with lime wedge and candied ginger.', 2, 'Easy', 'https://images.unsplash.com/photo-1567696911980-2eed69a46042', 'Modern'),
('Dark n Stormy', 'Bermudian cocktail with dark rum and ginger beer', '2 oz Dark Rum, 4 oz Ginger Beer, 0.5 oz Fresh Lime Juice, Lime wedge for garnish', '1. Fill highball glass with ice. 2. Add lime juice and ginger beer. 3. Float dark rum on top. 4. Garnish with lime wedge.', 2, 'Easy', 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd', 'Classic'),
('Aperol Spritz', 'Italian aperitif perfect for summer', '3 oz Prosecco, 2 oz Aperol, 1 oz Soda Water, Orange slice for garnish', '1. Fill wine glass with ice. 2. Add Aperol, then Prosecco. 3. Top with soda water. 4. Stir gently and garnish with orange slice.', 1, 'Easy', 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a', 'Modern'),
('French 75', 'Elegant champagne cocktail with gin and lemon', '1 oz Gin, 0.5 oz Fresh Lemon Juice, 0.5 oz Simple Syrup, 2 oz Champagne, Lemon twist for garnish', '1. Add gin, lemon juice, and simple syrup to shaker with ice. 2. Shake well. 3. Strain into champagne flute. 4. Top with champagne. 5. Garnish with lemon twist.', 4, 'Medium', 'https://images.unsplash.com/photo-1544148103-0773bf10d330', 'Classic'),
('Bloody Mary', 'Savory tomato-based cocktail perfect for brunch', '2 oz Vodka, 4 oz Tomato Juice, 0.5 oz Lemon Juice, 2 dashes Worcestershire, 2 dashes Hot Sauce, Pinch of Salt and Pepper, Celery stick for garnish', '1. Add all ingredients except garnish to shaker with ice. 2. Shake gently. 3. Strain into tall glass over ice. 4. Garnish with celery stick and your choice of pickles, olives, or bacon.', 3, 'Medium', 'https://images.unsplash.com/photo-1571104508999-893933ded431', 'Brunch'),
('Mint Julep', 'Traditional Southern cocktail with bourbon and mint', '2.5 oz Bourbon, 0.5 oz Simple Syrup, 8-10 Fresh Mint Leaves, Crushed Ice, Fresh mint sprig for garnish', '1. Muddle mint leaves with simple syrup in julep cup. 2. Add bourbon and fill with crushed ice. 3. Stir until cup frosts. 4. Top with more crushed ice and garnish with mint sprig.', 4, 'Medium', 'https://images.unsplash.com/photo-1544148103-0773bf10d330', 'Classic'),
('Sazerac', 'New Orleans classic with rye whiskey and absinthe', '2 oz Rye Whiskey, 0.25 oz Simple Syrup, 2 dashes Peychauds Bitters, Absinthe rinse, Lemon peel for garnish', '1. Rinse chilled rocks glass with absinthe. 2. In mixing glass, muddle sugar with bitters. 3. Add whiskey and ice, stir well. 4. Strain into prepared glass. 5. Express lemon peel oils over drink and discard peel.', 6, 'Hard', 'https://images.unsplash.com/photo-1514933651103-005eec06c04b', 'Classic'),
('Aviation', 'Gin cocktail with maraschino and crème de violette', '2 oz Gin, 0.5 oz Maraschino Liqueur, 0.25 oz Crème de Violette, 0.75 oz Fresh Lemon Juice, Maraschino cherry for garnish', '1. Add all ingredients to shaker with ice. 2. Shake well. 3. Double strain into chilled coupe glass. 4. Garnish with maraschino cherry.', 4, 'Medium', 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a', 'Classic');
