// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnghsontedmmqtkuatmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZ2hzb250ZWRtbXF0a3VhdG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjQxODIsImV4cCI6MjA2NDk0MDE4Mn0.sMSo6R59txkipENklQp9CixHRWoO4MGZuvKRi1Rr7wE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);